Blog: Convert tests to Pester 5 for a DSC Community repository
dsccommunity/dsccommunity.org pull request #160
Opened 2020-12-28 14:47 UTC by johlju

2020-12-28 22:59 UTC, PlagueHO commented
Let me know when you're ready for review on this one @johlju !

2020-12-29 15:41 UTC, johlju commented
@PlagueHO I only have one section left, then I need to go through already converted test to see if there anything there to raise that I missed. I hope this is ready by tomorrow night. Writing it as more of a guideline than step-by-step. Writing it as a step-by-step is not possible because there are many variations.

2020-12-30 07:45 UTC, johlju commented
@Fiander 

In regards to `-Because`. You are welcome to use it but if so I think it should give more information that the `It`-block description. For example if the `It`-block description in your example above is 'Should not throw and return the correct values for the properties' then I don't think the `Because` brings brings more value. If `Because` is used I think it should add more information to why the value must be correct, that is give more information than what the `It`-block description gives. 🤔 Also when using `Because` the text should be phrased so it reads correct in the Pester output. For example the following:

```
$result | Should -Be 'MyAlertName2' -Because 'the correct alert name must be returned when the alert does not exist so user knows what alert failed'
```

Would result in the following that reads naturally:
```
Expected strings to be the same, because the correct alert name must be returned when the alert does not exist so user knows what alert failed, but they were different.
 Expected length: 12
 Actual length:   11
 Strings differ at index 11.
 Expected: 'MyAlertName2'
 But was:  'MyAlertName'
```

I can add this to the blog post.

In regards to your questions regarding exceptions and localized strings I will cover that in the section I didn't had time to complete yesterday. 🙂  But short story, since you are in the module scope you have access to `$script:localizedData`, e.g. `$script.localizedData.FailedToGetSqlServerProtocol` so you can get the expected error message in the test.
You also need to use `Should -Throw -ExpectedMessage ($mockErrorRecord.Exception.Message + '*`)`, but you can use your suggestion too `"$($mockErrorRecord.Exception.Message)*"`. I agree the `*` is necessary because Pester 5 does not longer does a "contains" check on the error message, but instead a "like" comparison. 

I think we should get the test helper function `Get-InvalidOperationRecord` and `Get-InvalidResultRecord` to add the wildcard `*` to the message. Maybe two parameters `WildcardPrefix` and `WildcardSuffix`. We can do that when we move the test helper function (CommonTestHelper) to DscResource.Test.

2020-12-30 09:37 UTC, johlju commented
@PlagueHO Could you please review (proof read) when you have time. If it is very much changes and if it is faster you are welcome to push commits to the working branch. 🙂 Happy to to add sections if we are missing something.

@Fiander you have new sections around asserting exceptions now. 😃

2020-12-31 10:34 UTC, johlju commented
@PlagueHO some minor grammar fixed thanks to my girlfriend. Hopefully we proactively squashed a few potential review comments. 😄

2020-12-31 23:12 UTC, PlagueHO requested changes
Great stuff @johlju - I understand the conversion process much better now. It seems it is also more about applying a more atomic structure to test design - which is something I'd sporadically been working on when I make changes to resources. So, some resources will be easier to convert than others. But still a _massive_ amount of work for more resources.

> Reviewed 1 of 2 files at r1, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-:-MPv3P82DixCRRorTf2O:b4kfnev)* status: all files reviewed, 47 unresolved discussions (waiting on @johlju)

___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 54 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPuf2oL0y5q7Su4mwTb:-MPuf2oL0y5q7Su4mwTc:b-ry5d1n) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L54)):*
> ```Markdown
> ## Before we start, a note about self-sustaining tests
> 
> We developers have a number one rule that it is bad to duplicate code and
> ```

could refer to DRY?
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 57 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPubmHjCWwmbDcUnF9Y:-MPubmHjCWwmbDcUnF9Z:bjd3v1e) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L57)):*
> ```Markdown
> instead code should be reused. It is normally good to reuse code, but when
> it comes to writing Pester tests this can be bad thing. Reusing code leads
> to tests not being self-sustaining and tests can become very complex for
> ```

self-sustaining might read clearer as "atomic" or "self-contained".
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 61 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPuc-Li3L7r80eKHhYo:-MPuc-Li3L7r80eKHhYp:bb0616j) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L61)):*
> ```Markdown
> 
> I have seen the need, both as a contributor and maintainer helping contributors
> with Pester tests, to write the tests more simple. Both so that contributors
> ```

write the tests more simple -> simplify the tests.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 62 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPucRca6ExGBi2gt5Vq:-MPucRca6ExGBi2gt5Vr:b-ujhmo0) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L62)):*
> ```Markdown
> I have seen the need, both as a contributor and maintainer helping contributors
> with Pester tests, to write the tests more simple. Both so that contributors
> them self can update tests, secondly so that a maintainer more easily can
> ```

them self -> themselves
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 63 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPucZSU8WGYsEyvPy0Z:-MPucZSU8WGYsEyvPy0_:b-xl3t6) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L63)):*
> ```Markdown
> with Pester tests, to write the tests more simple. Both so that contributors
> them self can update tests, secondly so that a maintainer more easily can
> help contributors by giving pointers where in the tests a change needs to
> ```

Might read better as: secondly so that maintainers can more easily give pointers to contributors on how tests can be improved.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 67 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPucpdnA2AGUcx5N5-4:-MPucpdnA2AGUcx5N5-5:b5tghhe) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L67)):*
> ```Markdown
> 
> **In my experience the number one reason for pull request to be abandoned**
> **is because tests are too hard to learn to write, which ends us up at the**
> ```

which ends us up at the second reason -> which leads us to the another challenge
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 70 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPued9N9b1H5GKy_H1A:-MPued9N9b1H5GKy_H1B:b-6thbw6) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L70)):*
> ```Markdown
> **second reason... bandwidth for both contributor and maintainer.**
> 
> So what is a self-sustaining test? I would like to describe it as where
> ```

self-sustaining -> "self-contained" or "atomic"
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 72 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPuek3e9_QssY_2plZk:-MPuek3e9_QssY_2plZl:b59840p) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L72)):*
> ```Markdown
> So what is a self-sustaining test? I would like to describe it as where
> the mocks, the call to the function being tested, and the asserts of the
> result are very close together, preferably nested in one or more
> ```

"very close together" -> could be changed to "are contained an a self-contained atomic code block, usually a `context` block."
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 76 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPufSNzEwXgnIl0c8xS:-MPufSNzEwXgnIl0c8xT:b6wa1bz) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L76)):*
> ```Markdown
> without needing to scroll up and down in the code. It will be easy for
> contributors to find the right test to modify for the change they are
> making by just reading one or two pages of code. This means not to be
> ```

This means not to be afraid to duplicate code -> This means not being afraid to duplicate code
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 78 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPufZGBBxg3ZosK-D6V:-MPufZGBBxg3ZosK-D6W:baj9gbb) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L78)):*
> ```Markdown
> making by just reading one or two pages of code. This means not to be
> afraid to duplicate code! You may think that the code will be slower to
> run if there is more code, but honestly it can be faster than having a
> ```

but honestly - but in reality
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 86 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPuflPJ0MbwCkcVlLo-:-MPuflPJ0MbwCkcVlLo0:b34u98h) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L86)):*
> ```Markdown
> `Get-ServerProtocolObject` could be easily moved out from each test and
> moved into a separate `BeforeAll`-block in a parent `Context`-block. This
> is what developers instinctively want to do. But what happens if we would
> ```

if  [...]

2021-01-01 11:13 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160)* status: 1 of 2 files reviewed, 47 unresolved discussions (waiting on @PlagueHO)

___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 54 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPuf2oL0y5q7Su4mwTb:-MPx_SzW3k0wCEu1Y0yZ:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L54)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

could refer to DRY?
</blockquote></details>

Done.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 57 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPubmHjCWwmbDcUnF9Y:-MPx_U0274cmPfu1u9ID:b-d17po5) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L57)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

self-sustaining might read clearer as "atomic" or "self-contained".
</blockquote></details>

Done. Thanks! I used self-contained since the word atomic feels like it is more used in workloads where "only one thing should be responsible for doing that thing", the opposite of having code duplication.  :thinking: 
Self-contained felt like a better word instead of self-sustained.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 61 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPuc-Li3L7r80eKHhYo:-MPxan3y-jLrrU6J0efA:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L61)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

write the tests more simple -> simplify the tests.
</blockquote></details>

Done.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 62 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPucRca6ExGBi2gt5Vq:-MPxaolmEiBDK_sG9Fpz:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L62)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

them self -> themselves
</blockquote></details>

Done.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 63 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPucZSU8WGYsEyvPy0Z:-MPxasha4WdZBsqmcO9V:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L63)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Might read better as: secondly so that maintainers can more easily give pointers to contributors on how tests can be improved.
</blockquote></details>

Done.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 67 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPucpdnA2AGUcx5N5-4:-MPxav-PEYh9kysvk7rs:b-8gxapi) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L67)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

which ends us up at the second reason -> which leads us to the another challenge
</blockquote></details>

Done. I'm not sure what you thought here (it snuck in a typo :wink: ), but I went with "which leads us to the other challenge" instead of "which leads us to another challenge". The word "other" felt like it pointed to the second biggest reason.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 70 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPued9N9b1H5GKy_H1A:-MPxbap34nJLZXnOYneU:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L70)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

self-sustaining -> "self-contained" or "atomic"
</blockquote></details>

Done.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 72 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPuek3e9_QssY_2plZk:-MPxbf9jE1feJRKbr6bq:b2tx7cb) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L72)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

"very close together" -> could be changed to "are contained an a self-contained atomic code block, usually a `context` block."
</blockquote></details>

Done. I kept the "atomic" here for people to see that word too. 
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 76 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPufSNzEwXgnIl0c8xS:-MPxbnkd466XSwIEmFHm:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L76)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

This means not to be afraid to duplicate code -> This means not being afraid to duplicate code
</blockquote></details>

Done.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 78 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPufZGBBxg3ZosK-D6V:-MPxbo87EDVRsY9114O2:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L78)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

but honestly - but in reality
</blockquote></details>

Done.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 86 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPuflPJ0MbwCkcVlLo-:-MPxbpRO1gIC1J8DlsbV:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L86)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

if we would -> if we
</blockquote></details>

Done.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 97 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPugvpI0wNXykhVWkA3:-MPxbpuu0_c9tSJQQj3L:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L97)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

self-contained
</blockquote></details>

Done.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 100 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPuh1I838e-E3-fQN5r:-MPxbqX9CDYGcIBQ03xt:b-896fix) ([raw file](https://github.com/dsccommunity/d [...]

2021-01-01 11:14 UTC, johlju commented
@PlagueHO thanks for all the review comments! Rephrased a couple of sections as per your suggestion. Ready for review again. 😃  Happy new year! 🎆

2021-01-06 19:49 UTC, PlagueHO commented
Happy New Year! I'll review later on today!

2021-01-07 22:19 UTC, PlagueHO requested changes
@johlju - just two tiny tweaks and good to go! Great job @johlju !!!

> Reviewed 1 of 1 files at r7.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-:-MQTvgdO7siZz5TdIMTk:b3hldv4)* status: all files reviewed, 2 unresolved discussions (waiting on @johlju)

___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 67 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPucpdnA2AGUcx5N5-4:-MQTrH3L1ykUHq7Flju9:btzq7em) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L67)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. I'm not sure what you thought here (it snuck in a typo :wink: ), but I went with "which leads us to the other challenge" instead of "which leads us to another challenge". The word "other" felt like it pointed to the second biggest reason.
</blockquote></details>

Oops yep - my bad :D Both would have worked. 
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 253 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPuiry97yIySeI2vtoT:-MQTtSnmANiKYLUraNQP:bi0rogs) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L253)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. I rephrased the whole paragraph. Hopefully it is clearer now. :slightly_smiling_face: 
</blockquote></details>

Great job!
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 260 at r5](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MPujPUD2jNUtSeIzN2M:-MQTtfwM0ghwXWU5dtpu:b-hsemkn) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/4b8d5912002b34a3f4227c61c9d1c0e68427618c/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L260)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Discovery and Run is Pester terms, I clarified that.
</blockquote></details>

Ah I see!
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 977 at r7](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MQTuv--AE4vr8fEpHtA:-MQTuv--AE4vr8fEpHtB:b-5wfzwd) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/787ff28da9169722a91724968a59f5ec2a4a30cb/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L977)):*
> ```Markdown
> number of calls throughout all the `It`-blocks. Was it 8 calls from one
> `It`-block or was it 2 calls from two `It`-blocks, and is one
> `It`-block doing 3 calls. Why is that if the other ones don't, is that
> ```

Why is that if the other ones don't, is that correct? ->
Why is that, if the other ones don't? Is that correct?
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 981 at r7](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MQTuw8VAfMpelj4d6GW:-MQTuw8VAfMpelj4d6GX:b-npv1m2) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/787ff28da9169722a91724968a59f5ec2a4a30cb/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L981)):*
> ```Markdown
> number of expected number of hits should be. Use this wisely, and make use
> of the parameter `ParameterFilter` where possible to split up the asserts.
> If that is not possible consider adding an unique helper function for each
> ```

adding an unique -> adding a unique


<!-- Sent from Reviewable.io -->

2021-01-08 08:22 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160)* status: 1 of 2 files reviewed, 2 unresolved discussions (waiting on @PlagueHO)

___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 977 at r7](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MQTuv--AE4vr8fEpHtA:-MQW4kTm9o0Yho2Xpymt:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/787ff28da9169722a91724968a59f5ec2a4a30cb/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L977)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Why is that if the other ones don't, is that correct? ->
Why is that, if the other ones don't? Is that correct?
</blockquote></details>

Done.
___
*[content/blog/convert-tests-to-pester5-for-dsc-community-repository.md, line 981 at r7](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-MQTuw8VAfMpelj4d6GW:-MQW4lDe3iP-Y18E7qwF:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/787ff28da9169722a91724968a59f5ec2a4a30cb/content/blog/convert-tests-to-pester5-for-dsc-community-repository.md#L981)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

adding an unique -> adding a unique
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-01-08 08:23 UTC, johlju commented
@PlagueHO ready for sign off now 🙂

2021-01-08 08:32 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r8.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/160#-:-MQW6zE5E5B5XhXnMvwv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)



<!-- Sent from Reviewable.io -->

2021-01-08 08:32 UTC, merged