Add first to sections
dsccommunity/dsccommunity.org pull request #169
Opened 2021-04-09 17:09 UTC by johlju

2021-04-09 22:51 UTC, PlagueHO reviewed
Looks great @johlju - and now I know what to do :grin:

Just some minor tweaks

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-:-MXspJknAcdx1_qp3lI-:bjcltry)* status: all files reviewed, 9 unresolved discussions (waiting on @johlju)

___
*[content/blog/add-codecov-support-to-repository.md, line 10 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsmiUK9s16t-VRw5TN:-MXsmiUK9s16t-VRw5TO:b5jjldz) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L10)):*
> ```Markdown
> 
> _This assumes the repository is using the pattern from the [Sampler](https://github.com/gaelcolas/Sampler)_
> _project. Also make sure to have update the repository to the latest pipeline_
> ```

Also make sure you have updated the repository to the latest pipeline.

(Include full stop)
___
*[content/blog/add-codecov-support-to-repository.md, line 16 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsmdmD-3g3R_gZNDh6:-MXsmdmD-3g3R_gZNDh7:b5y1zpi) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L16)):*
> ```Markdown
> 
> - [Introduction](#introduction)
> - [Not building module, just copies files](#not-building-module-just-copies-files)
> ```

Could be:
Just copies files -> just copying files
___
*[content/blog/add-codecov-support-to-repository.md, line 34 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsn7110m3MIxmnxFKk:-MXsn7110m3MIxmnxFKl:b-804mk) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L34)):*
> ```Markdown
> >Pipelines code coverage will not find source files in certain circumstances.
> >When a repository is using the pattern from the [Sampler](https://github.com/gaelcolas/Sampler)
> >project then paths that is copied (not built) from source by ModuleBuilder.
> ```

then paths that is copied (not built) -> then the paths are copied (not built)
___
*[content/blog/add-codecov-support-to-repository.md, line 36 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsn_omA9ww1DbXkfNc:-MXsn_omA9ww1DbXkfNd:ba25atv) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L36)):*
> ```Markdown
> >project then paths that is copied (not built) from source by ModuleBuilder.
> >For example MOF-resources do show coverage for the entire file, but not on
> >individual code lines since the source file is not found by the task
> ```

source file is not found -> source file can not be found
___
*[content/blog/add-codecov-support-to-repository.md, line 48 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsnukW8tQlrVWXRMx-:-MXsnukW8tQlrVWXRMx0:b50tjzx) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L48)):*
> ```
> to change the `build.yaml`, add a `codecov.yml`
> ```
change to:
to change the `build.yaml` by adding a `codecov.yml`
___
*[content/blog/add-codecov-support-to-repository.md, line 216 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsoa243K81pGZA5oEL:-MXsoa243K81pGZA5oEM:b-2zzw2q) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L216)):*
> ```Markdown
> 
> These settings can be set as wanted, but the below is the default values
> that we have used in the DSC Community repositories.
> ```

These settings can be set as wanted, but the below is the default values
that we have used in the DSC Community repositories.
->
These settings can be set as desired, but the values below are what are used by
default in the DSC Community repositories.
___
*[content/blog/add-codecov-support-to-repository.md, line 278 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsp1VJ1K4nB8A6TaYL:-MXsp1VJ1K4nB8A6TaYM:b-p53zjh) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L278)):*
> ```
> If the repository is building whole or part of the module using the ModuleBuilder
> ```

Could be:
If the repository is building all or just part of the module using the ModuleBuilder
___
*[content/blog/add-codecov-support-to-repository.md, line 279 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsp5ng9rbHdA3Tf7LK:-MXsp5ng9rbHdA3Tf7LL:bm9j28r) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L279)):*
> ```Markdown
> 
> If the repository is building whole or part of the module using the ModuleBuilder
> pattern of `Private`, `Public`, `Classes` and or `Enum`. E.g. combination of
> ```

and or -> and/or
___
*[content/blog/add-codecov-support-to-repository.md, line 280 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXspA_mDuiRbReG_Nck:-MXspA_mDuiRbReG_Ncl:bm9j28r) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L280)):*
> ```Markdown
> If the repository is building whole or part of the module using the ModuleBuilder
> pattern of `Private`, `Public`, `Classes` and or `Enum`. E.g. combination of
> class-based and MOF-based resources, and or public/private functions.
> ```

and or -> and/or


<!-- Sent from Reviewable.io -->

2021-04-10 01:15 UTC, PlagueHO reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169)* status: all files reviewed, 12 unresolved discussions (waiting on @johlju)

___
*[content/blog/add-codecov-support-to-repository.md, line 93 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXtGSaq2-2bt6g2qJZO:-MXtGSaq2-2bt6g2qJZP:b-lv327o) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L93)):*
> ```Markdown
> following.
> 
> ```yaml
> ```

Can you add a screenshot or example of what this will look like after? E.g.
```yaml
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - source/*
  tags:
    include:
    - "v*"
    exclude:
    - "*-*"

variables:
  buildFolderName: output
  buildArtifactName: output
  testResultFolderName: testResults
  testArtifactName: testResults
  sourceFolderName: source
```
___
*[content/blog/add-codecov-support-to-repository.md, line 104 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXtH1uq4ZuX7XCkhcuj:-MXtH1urA0UUvyTepIRH:b3e6bdm) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L104)):*
> ```Markdown
> #### Update job `Test_Unit`
> 
> The tasks of this job are:
> ```

Is it possible to clarify if anything needs to be done here? When I was converting StorageDsc I wasn't 100% clear if I actually needed to update anything because it all looked the same (mostly) - except for the paths using variables... Or is this just a checklist of things that need to be included?
___
*[content/blog/add-codecov-support-to-repository.md, line 194 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXtJ2bx1m-QG410FS6X:-MXtJ2bx1m-QG410FS6Y:b-7pnwl7) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L194)):*
> ```Markdown
>               targetPath: '$(Build.SourcesDirectory)/$(buildFolderName)/$(testResultFolderName)'
>           - task: PublishCodeCoverageResults@1
>             displayName: 'Publish Azure Code Coverage'
> ```

Can the display name read something like `Publish Code Coverage to Azure DevOps` - it caught me at first as "why are we uploading code coverage to Azure?" :grin:


<!-- Sent from Reviewable.io -->

2021-04-11 12:18 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169)* status: 0 of 1 files reviewed, 12 unresolved discussions (waiting on @PlagueHO)

___
*[content/blog/add-codecov-support-to-repository.md, line 10 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsmiUK9s16t-VRw5TN:-MY-qr8a78GcCNtzM3RW:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L10)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Also make sure you have updated the repository to the latest pipeline.

(Include full stop)
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 16 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsmdmD-3g3R_gZNDh6:-MY-qrum1aAVHOqQwSN5:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L16)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Could be:
Just copies files -> just copying files
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 34 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsn7110m3MIxmnxFKk:-MY-qvmQ1bjyzrguNQRD:b-ogac7y) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L34)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

then paths that is copied (not built) -> then the paths are copied (not built)
</blockquote></details>

Done. Rephrased it a bit, see it is better.
___
*[content/blog/add-codecov-support-to-repository.md, line 36 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsn_omA9ww1DbXkfNc:-MY-rEov58YoDVxISFW3:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L36)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

source file is not found -> source file can not be found
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 48 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsnukW8tQlrVWXRMx-:-MY-rGvB8YTEyPGWkDpS:b-kx1a3s) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L48)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> to change the `build.yaml`, add a `codecov.yml`
> ```
change to:
to change the `build.yaml` by adding a `codecov.yml`
</blockquote></details>

Done. Rephrased the entire section to hopefully more accurately explain what I meant.
___
*[content/blog/add-codecov-support-to-repository.md, line 93 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXtGSaq2-2bt6g2qJZO:-MY-rQCZ7lxOu24RLOKl:bfaaifj) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L93)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can you add a screenshot or example of what this will look like after? E.g.
```yaml
trigger:
  branches:
    include:
    - main
  paths:
    include:
    - source/*
  tags:
    include:
    - "v*"
    exclude:
    - "*-*"

variables:
  buildFolderName: output
  buildArtifactName: output
  testResultFolderName: testResults
  testArtifactName: testResults
  sourceFolderName: source
```
</blockquote></details>

Done. Also tried to implement this throughout.
___
*[content/blog/add-codecov-support-to-repository.md, line 104 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXtH1uq4ZuX7XCkhcuj:-MY-rTGSB6LKrgmSQo97:b-gufobx) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L104)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Is it possible to clarify if anything needs to be done here? When I was converting StorageDsc I wasn't 100% clear if I actually needed to update anything because it all looked the same (mostly) - except for the paths using variables... Or is this just a checklist of things that need to be included?
</blockquote></details>

Done. Hopefully better.
___
*[content/blog/add-codecov-support-to-repository.md, line 194 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXtJ2bx1m-QG410FS6X:-MY-rXKp-X_EuMNC36ON:b-15yn82) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L194)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can the display name read something like `Publish Code Coverage to Azure DevOps` - it caught me at first as "why are we uploading code coverage to Azure?" :grin:
</blockquote></details>

Done. Haha sure. Didn't want it to be too long, but this works.
___
*[content/blog/add-codecov-support-to-repository.md, line 216 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsoa243K81pGZA5oEL:-MY-rbHSAbDHMeyyxdd5:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L216)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

These settings can be set as wanted, but the below is the default values
that we have used in the DSC Community repositories.
->
These settings can be set as desired, but the values below are what are used by
default in the DSC Community repositories.


</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 278 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsp1VJ1K4nB8A6TaYL:-MY-rbwSBY5zy2mrodse:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L278)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

> ```
> If the repository is building whole or part of the module using the ModuleBuilder
> ```

Could be:
If the repository is building all or just part of the module using the ModuleBuilder
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 279 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXsp5ng9rbHdA3Tf7LK:-MY-rcyN0millR2N6pL1:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L279)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

and or -> and/or
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 280 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXspA_mDuiRbReG_Nck:-MY-rdGd6rqFGz8Y3NJK:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L280)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

and or -> and/or
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

2021-04-11 12:19 UTC, johlju commented
@PlagueHO repharsed and updated sections, and added the last "merge" section.

2021-04-17 20:55 UTC, PlagueHO requested changes
Ah, I see that the pipeline definition tasks have changed a bit in the past month or so (been too busy to notice). I'm still using old tasks, so will need to update all pipelines.

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-:-MYWZbok1YzhoFsM19_2:bnzdkt7)* status: all files reviewed, 16 unresolved discussions (waiting on @johlju and @PlagueHO)

___
*[content/blog/add-codecov-support-to-repository.md, line 411 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_4Cp1iib3rM6GJb2:-MYW_4Cp1iib3rM6GJb3:b9orjdf) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L411)):*
> ```Markdown
> ## Code coverage for multiple jobs
> 
> If a repository need to gather code coverage from more than one job,
> ```

need -> needs
___
*[content/blog/add-codecov-support-to-repository.md, line 415 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_CO-D7C8aW9PIR6n:-MYW_CO-D7C8aW9PIR6o:b-ki9piu) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L415)):*
> ```Markdown
> or both services Azure DevOps or Codecov.io.
> 
> For example unit tests or integration tests are run on multiple operating
> ```

For example -> For example, 
___
*[content/blog/add-codecov-support-to-repository.md, line 417 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_GSxBvzmPh7T9bvE:-MYW_GSxBvzmPh7T9bvF:b3j1ccq) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L417)):*
> ```Markdown
> For example unit tests or integration tests are run on multiple operating
> systems and/or target multiple versions of an application. It might be that
> one functionality can only be tested on a certain version/operating system
> ```

one functionality -> some functions
___
*[content/blog/add-codecov-support-to-repository.md, line 418 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_a3DCXS_wxI7I-zD:-MYW_a3DCXS_wxI7I-zE:bmhmxhs) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L418)):*
> ```Markdown
> systems and/or target multiple versions of an application. It might be that
> one functionality can only be tested on a certain version/operating system
> and other functionality can only be tested on a different version/operating
> ```

and other functions -> while other functions
___
*[content/blog/add-codecov-support-to-repository.md, line 427 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_rY14G-VS6f5Adt5:-MYW_rY14G-VS6f5Adt6:b-eki2t0) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L427)):*
> ```Markdown
> ### Modify `build.yaml`
> 
> The filename `JaCoCo_coverage.xml` that have been used in the previous section
> ```

that have been -> that has been
___
*[content/blog/add-codecov-support-to-repository.md, line 428 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_o5w2VBeVASuaQCq:-MYW_o5w2VBeVASuaQCr:bsgu2rp) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L428)):*
> ```Markdown
> 
> The filename `JaCoCo_coverage.xml` that have been used in the previous section
> cannot be used for Pester when we need gather coverage from multiple jobs.
> ```

when we need gather -> when we need to gather
___
*[content/blog/add-codecov-support-to-repository.md, line 429 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_uBC0Em-U2IJtalU:-MYW_uBDCBpuPR5JwcV-:b-fweqy5) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L429)):*
> ```Markdown
> The filename `JaCoCo_coverage.xml` that have been used in the previous section
> cannot be used for Pester when we need gather coverage from multiple jobs.
> There are two options
> ```

Can add a colon at the end
___
*[content/blog/add-codecov-support-to-repository.md, line 435 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_xwGADLB4S32DOZ6:-MYW_xwGADLB4S32DOZ7:bkp3t17) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L435)):*
> ```Markdown
>   version and operating system (Linux, macOS, Windows) and with the prefix `Codecov_`
>   (short for 'Code Coverage').
> - or you add a different specific filename, which will be used for all jobs,
> ```

or you add -> or add
___
*[content/blog/add-codecov-support-to-repository.md, line 436 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWa-iT68olH1ZK2eRd:-MYWa-iT68olH1ZK2eRe:bf6o6s6) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L436)):*
> ```Markdown
>   (short for 'Code Coverage').
> - or you add a different specific filename, which will be used for all jobs,
>   for example 'JaCoCo_Merge.xml'.
> ```

for example -> for example,
___
*[content/blog/add-codecov-support-to-repository.md, line 438 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWa3C52LYWWikksjmM:-MYWa3C52LYWWikksjmN:b-63hz44) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L438)):*
> ```Markdown
>   for example 'JaCoCo_Merge.xml'.
> 
> Whatever you choose works, so choose one. Depending of choice, the code
> ```

Whatever you choose works, so choose one <- this sentence doesn't really seem to be necessary.

Depending of choice -> Depending on your choice
___
*[content/blog/add-codecov-support-to-repository.md, line 439 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWaF6IA7vTpumhWT1t:-MYWaF6IA7vTpumhWT1u:b75kd83) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L439)):*
> ```Markdown
> 
> Whatever you choose works, so choose one. Depending of choice, the code
> coverage job in Azure Pipelines need to take account for it. More on that
> ```

need to take account -> needs to take account
___
*[content/blog/add-codecov-support-to-repository.md, line 463 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWaWlP906s56zqARMW:-MYWaWlP906s56zqARMX:b-86xs53) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L463)):*
> ```Markdown
> ```
> 
> If you choose to remove the keyword, the `Pester` section can look like
> ```

choose to remove the keyword -> choose to remove `CodeCoverageOutputFile` keyword
___
*[content/blog/add-codecov-support-to-repository.md, line 495 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWah-nCHSGvznECdEv:-MYWah-nCHSGvznECdEw:b-mh5vqb) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L495)):*
> ```Markdown
> ```
> 
> The task _Merge\_CodeCoverage\_Files_ also need specific settings in the
> ```

also need -> also needs
___
*[content/blog/add-codecov-support-to-repository.md, line 496 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWajrhAMuL_P4_x_tl:-MYWajrhAMuL_P4_x_tm:bhxdr8z) ([raw f [...]

2021-04-18 08:23 UTC, johlju reviewed
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169)* status: 0 of 1 files reviewed, 16 unresolved discussions (waiting on @PlagueHO)

___
*[content/blog/add-codecov-support-to-repository.md, line 104 at r1](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MXtH1uq4ZuX7XCkhcuj:-MYZ3XQg4iqFGo83ZNxb:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/b0984ed963f13b382ab99ca029b9b8eb44b1ff45/content/blog/add-codecov-support-to-repository.md#L104)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Done. Hopefully better.
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 411 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_4Cp1iib3rM6GJb2:-MYZ3Y15CQ8fAzzeMxMN:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L411)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

need -> needs
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 415 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_CO-D7C8aW9PIR6n:-MYZ3Yg56UTivgsxeB2O:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L415)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

For example -> For example, 
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 417 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_GSxBvzmPh7T9bvE:-MYZ3ZC64POIatO753QL:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L417)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

one functionality -> some functions
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 418 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_a3DCXS_wxI7I-zD:-MYZ3_Wj58ebxURWcyBQ:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L418)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

and other functions -> while other functions
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 427 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_rY14G-VS6f5Adt5:-MYZ3af-2AG3Yb9G2_RP:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L427)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

that have been -> that has been
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 428 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_o5w2VBeVASuaQCq:-MYZ3bRiD90PnGCtxzMs:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L428)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

when we need gather -> when we need to gather
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 429 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_uBC0Em-U2IJtalU:-MYZ3cVe8nceOwj-Rn3G:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L429)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Can add a colon at the end
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 435 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYW_xwGADLB4S32DOZ6:-MYZ3dY7BN-qbloZESdW:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L435)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

or you add -> or add
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 436 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWa-iT68olH1ZK2eRd:-MYZ3eFo0gu9-RprOSLG:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L436)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

for example -> for example,
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 438 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWa3C52LYWWikksjmM:-MYZ3ewl9QN5X5EixA59:b-aa3rmt) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L438)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

Whatever you choose works, so choose one <- this sentence doesn't really seem to be necessary.

Depending of choice -> Depending on your choice
</blockquote></details>

Done. Removed the phrase that was not needed.
___
*[content/blog/add-codecov-support-to-repository.md, line 439 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWaF6IA7vTpumhWT1t:-MYZ3k043LNKD69fUvou:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L439)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

need to take account -> needs to take account
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 463 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWaWlP906s56zqARMW:-MYZ3kxC8g04Hu4_q9IU:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L463)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

choose to remove the keyword -> choose to remove `CodeCoverageOutputFile` keyword
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 495 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWah-nCHSGvznECdEv:-MYZ3lbZBQUAH9StY1Ey:b-896fix) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L495)):*
<details><summary><i>Previously, PlagueHO (Daniel Scott-Raynsford) wrote…</i></summary><blockquote>

also need -> also needs
</blockquote></details>

Done.
___
*[content/blog/add-codecov-support-to-repository.md, line 496 at r2](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-MYWajrhAMuL_P4_x_tl:-MYZ3m8w1cYsHyDAH2qn:bldaeht) ([raw file](https://github.com/dsccommunity/dsccommunity.org/blob/00f27f6eac4c2e453d7d054f184e7c474df9f833/content/blog/add-codecov-support-to-repository.md#L496)):*
<details><summary><i>Previously, Pla [...]

2021-04-19 06:55 UTC, PlagueHO approved these changes
<img class="emoji" title=":lgtm:" alt=":lgtm:" align="absmiddle" src="https://reviewable.io/lgtm.png" height="20" width="61"/>

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/169#-:-MYcuNvyCuk-gQu34b0r:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)



<!-- Sent from Reviewable.io -->

2021-04-19 06:55 UTC, merged