updating the DSC community call & resources
dsccommunity/dsccommunity.org pull request #189
Opened 2022-04-30 22:17 UTC by gaelcolas

2022-05-01 08:01 UTC, PlagueHO requested changes
The change looks fine, but looks like the build is failing. I'll see if I can take a look tomorrow.

> Reviewed 3 of 3 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/dsccommunity.org/189#-:-N0yceZXAmClgnHSvsam:bwl140s)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @johlju)



<!-- Sent from Reviewable.io -->

2022-05-01 08:17 UTC, johlju commented
/AzurePipelines run

2022-05-01 08:22 UTC, johlju commented on data/en/resources.json
> +      "updated": "2022-04-30T20:36:06Z",
Is it the format of the `updated` property it doesn't like? But the same format was used before, but other properties are using the format `30/04/2022 20:36:06 -07:00` 🤔

2022-05-01 08:24 UTC, johlju commented on data/en/resources.json
> +      "updated": "2022-04-30T20:16:06Z",
It seems to error on this line, the first one with yesterdays date `"2022-04-30T20:16:06Z",`

2022-05-02 21:39 UTC, gaelcolas commented
Thanks for your troubleshooting, I spotted that there were now 2 properties Updated and LastUpdated, with different date format.
I've updated the property to the Updated one which use the correct formatting for HUGO.

2022-05-02 21:40 UTC, merged